[package]
name = "audiokit-codec-opus"
description = "Exclusive per-stream Opus encoders and decoders for AudioKit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
audiokit = { path = "../audiokit", default-features = false }

opus.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
audiokit = { path = "../audiokit", features = ["resampling"] }

[lints]
workspace = true
